name: Make Documentation

on:
  push:
    branches: main
  pull_request:
    branches: main


jobs:
    build:
      runs-on: ${{ matrix.os }}

      strategy:
        matrix:
          os: [ubuntu-22.04]

      steps:
        - name: Install popper
          run: |
            sudo apt-get install -y poppler-utils

        - name: Checkout Repo
          uses: actions/checkout@v3

        - name: Install
          uses: actions/setup-python@v4
          with:
            python-version: '3.12'

        - name: Run installation.
          run: |
            python -m pip install --upgrade pip
            pip install -r docs/requirements.txt

        - name: Make docs
          run: |
            sphinx-build -b html docs build
            mkdir -p build/examples
            mkdir -p build/galleries
            cp docs/run_demo.sh ./
            bash run_demo.sh

        - name: Make example-for-nsfc-se
          uses: xu-cheng/latex-action@v2
          with:
            latexmk_use_xelatex: true
            root_file: |
              青年正文2024.tex
              青年正文2024-se.tex

        - name: Copy Demo to examples docs
          run: |
            cp 青年正文2024.pdf build/examples/
            cp 青年正文2024-se.pdf build/examples/ 

        - name: Make demo figures
          run: |
            python docs/pdf2imgs.py


        - name: Deploy Website
          uses: peaceiris/actions-gh-pages@v3
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./build
