jobs:
    build:
      runs-on: ${{ matrix.os }}

      strategy:
        matrix:
          os: [ubuntu-22.04]

      steps:
        - name: Install popper
          run: |
            sudo apt-get install -y poppler-utils

        - name: Checkout Repo
          uses: actions/checkout@v3

        - name: Install
          uses: actions/setup-python@v4
          with:
            python-version: '3.10'

        - name: Run installation.
          run: |
            python -m pip install --upgrade pip

        - name: Make docs
          run: |
            sphinx-build -b html docs build


        - name: Deploy Website
          uses: peaceiris/actions-gh-pages@v3
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./build
